name:                generic-boltzmann-brain
version:             0.1.0.0
github:              "maciej-bendkowski/generic-boltzmann-brain"
license:             BSD3
author:              "Maciej Bendkowski"
maintainer:          "maciej.bendkowski@gmail.com"
copyright:           "2022 Maciej Bendkowski"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Analytic sampler framework for algebraic data types
category:            Data, Generic, Random

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maciej-bendkowski/generic-boltzmann-brain#readme>

dependencies:
- base
- containers
- vector
- random
- transformers
- template-haskell
- th-abstraction
- th-lift-instances
- th-lift
- mtl
- paganini-hs
- QuickCheck
- splitmix
- data-default

library:
    source-dirs: api
    exposed-modules:
      Data.Boltzmann
    dependencies:
    - generic-boltzmann-brain-internal
    ghc-options:
    - -O2
    - -Wall
    - -Wcompat
    - -Wmissing-export-lists
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wno-name-shadowing
    - -fwarn-missing-signatures
    default-extensions:
      LambdaCase
      BangPatterns
      DerivingVia
      FlexibleInstances
      UndecidableInstances
      TypeApplications
      ScopedTypeVariables
      Rank2Types

internal-libraries:
  generic-boltzmann-brain-internal:
    source-dirs: internal
    ghc-options:
    - -O2
    - -Wall
    - -Wcompat
    - -Wmissing-export-lists
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wno-name-shadowing
    - -fwarn-missing-signatures
    default-extensions:
      LambdaCase
      BangPatterns
      DerivingVia
      FlexibleInstances
      UndecidableInstances
      TypeApplications
      ScopedTypeVariables
      Rank2Types

benchmarks:
  generic-boltzmann-brain:
    source-dirs: bench
    main:        Main.hs
    ghc-options:
    - -O2
    - -Wall
    - -Wcompat
    - -Wmissing-export-lists
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wno-name-shadowing
    - -fwarn-missing-signatures
    - -ddump-splices
    default-extensions:
      NumericUnderscores
      LambdaCase
      BangPatterns
      DerivingVia
      FlexibleInstances
      UndecidableInstances
      TypeApplications
      ScopedTypeVariables
      Rank2Types
    dependencies:
    - generic-boltzmann-brain
    - criterion
    - deepseq
    - QuickCheck

tests:
  generic-boltzmann-brain-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -O2
    - -Wall
    - -Wcompat
    - -Wmissing-export-lists
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wno-name-shadowing
    - -fwarn-missing-signatures
    - -ddump-splices
    dependencies:
    - generic-boltzmann-brain-internal
    - generic-boltzmann-brain
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
    default-extensions:
      NumericUnderscores
      LambdaCase
      BangPatterns
      DerivingVia
      FlexibleInstances
      UndecidableInstances
      TypeApplications
      ScopedTypeVariables
      Rank2Types
